# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
	# check these on https://modmuss50.me/fabric.html
#	minecraft_version=1.21.6
#	yarn_mappings=1.21.6+build.1
	loader_version=0.16.14
#	fabric_version=0.128.2+1.21.6


# Mod Properties
	mod_version = 1.21.4(8)-1.0.6
	maven_group = org.example.sansrus
	archives_base_name = simpleautoclicker


#minecraft_version=1.21.8
#yarn_mappings=1.21.8+build.1
#fabric_version=0.130.0+1.21.8

fabric_version=0.128.1+1.21.7
minecraft_version=1.21.7
yarn_mappings=1.21.7+build.6

#fabric_version=0.119.4+1.21.4
#minecraft_version=1.21.4
#yarn_mappings=1.21.4+build.8

#fabric_version=0.114.1+1.21.3	/not support
#minecraft_version=1.21.3		/not support
#yarn_mappings=1.21.3+build.2	/not support

#fabric_version=0.134.0+1.21.9	/not support
#minecraft_version=1.21.9	 	/not support
#yarn_mappings=1.21.9+build.1 	/not support